swagger: "2.0"
info:
  title: Happy Birthday API
  description: Takes a name in parameter and returns a happy birthday message to that name
  version: 0.1.0

host: almabase-task-avinash-rath.herokuapp.com
schemes: 
  - https
  - http

paths:
  /sendName:
    get:
      summary: Takes single parameter name and return a happy birthday message to that name
      description: e.g. if name = "Elon Musk", then response message = "Happy Birthday, Elon Musk!"
      parameters:
        - in: query
          name: name
          required: true
          type: string
          minimum: 1
          description: name of the person to wish a happy birthday
      produces:
        - application/text
      responses:
        200:
          description: Happy Birthday, "name"!
          schema:
            type: string
        400:
          description: Bad Request, did not send "name" param
          schema:
            type: string